#!/bin/bash
# VPS Setup Script for SEO Prerendering
# Run on Ubuntu/Debian VPS with: sudo bash setup-vps.sh

set -e

echo "=========================================="
echo "VPS SEO Prerender Setup"
echo "=========================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
DOMAIN="yourdomain.com"  # CHANGE THIS!
SPA_DIR="/var/www/your-site"
PRERENDER_DIR="/var/www/prerender"

# Prompt for domain
read -p "Enter your domain name (e.g., example.com): " DOMAIN
echo ""

# 1. System Update
echo -e "${YELLOW}[1/8] Updating system...${NC}"
sudo apt update && sudo apt upgrade -y

# 2. Install Node.js 20.x
echo -e "${YELLOW}[2/8] Installing Node.js 20.x...${NC}"
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt install -y nodejs
node --version
npm --version

# 3. Install Nginx
echo -e "${YELLOW}[3/8] Installing Nginx...${NC}"
sudo apt install -y nginx

# 4. Install Redis (for caching)
echo -e "${YELLOW}[4/8] Installing Redis...${NC}"
sudo apt install -y redis-server
sudo systemctl enable redis-server
sudo systemctl start redis-server

# 5. Install PM2 for process management
echo -e "${YELLOW}[5/8] Installing PM2...${NC}"
sudo npm install -g pm2

# 6. Setup Prerender Service
echo -e "${YELLOW}[6/8] Setting up Prerender service...${NC}"
sudo mkdir -p $PRERENDER_DIR
sudo chown -R $USER:$USER $PRERENDER_DIR

# Create package.json if not exists
if [ ! -f "$PRERENDER_DIR/package.json" ]; then
  cat > $PRERENDER_DIR/package.json << 'EOF'
{
  "type": "module",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.18.2",
    "playwright": "^1.40.0",
    "redis": "^4.6.0"
  }
}
EOF
fi

# Install dependencies
cd $PRERENDER_DIR
npm install

# Install Playwright browsers
npx playwright install chromium

# Create server.js if not exists
if [ ! -f "$PRERENDER_DIR/server.js" ]; then
  echo "⚠️  Please copy prerender/server.js to $PRERENDER_DIR/server.js"
  echo "   Or create it manually with your SPA URL configuration"
fi

# 7. Setup SPA directory
echo -e "${YELLOW}[7/8] Setting up SPA directory...${NC}"
sudo mkdir -p $SPA_DIR
sudo chown -R $USER:$USER $SPA_DIR

# 8. Configure Nginx
echo -e "${YELLOW}[8/8] Configuring Nginx...${NC}"
sudo mkdir -p /etc/nginx/sites-available
sudo mkdir -p /etc/nginx/sites-enabled
sudo mkdir -p /etc/nginx/conf.d
sudo mkdir -p /var/cache/nginx/prerender
sudo chown -R www-data:www-data /var/cache/nginx

# Create cache config
sudo tee /etc/nginx/conf.d/cache.conf > /dev/null << 'EOF'
proxy_cache_path /var/cache/nginx/prerender
    levels=1:2
    keys_zone=prerender_cache:10m
    max_size=1g
    inactive=1h
    use_temp_path=off;
EOF

# Create site config
sudo tee /etc/nginx/sites-available/$DOMAIN > /dev/null << EOF
# Nginx configuration for $DOMAIN
# Auto-generated by setup-vps.sh

map \$http_user_agent \$is_bot {
    default 0;
    ~*(google|bing|slurp|duckduck|baidu|yandex)bot 1;
    ~*facebookexternalhit 1;
    ~*TwitterBot 1;
    ~*LinkedInBot 1;
    ~*WhatsApp 1;
    ~*TelegramBot 1;
    ~*AppleBot 1;
}

upstream prerender {
    server localhost:3000;
    keepalive 32;
}

server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN www.$DOMAIN;

    # SSL (configure after certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root $SPA_DIR;
    index index.html;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|webp|svg|ico|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Sitemap & robots.txt
    location = /sitemap.xml {
        expires 1h;
        add_header Cache-Control "public";
        try_files \$uri /;
    }

    location = /robots.txt {
        expires 1d;
        add_header Cache-Control "public";
        try_files \$uri /;
    }

    # Main routing
    location / {
        if (\$is_bot = 1) {
            proxy_pass http://prerender;
            break;
        }
        try_files \$uri \$uri/ /index.html;
    }
}
EOF

# Enable site
sudo ln -sf /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/

# Remove default site
sudo rm -f /etc/nginx/sites-enabled/default

# Test Nginx config
sudo nginx -t

echo ""
echo -e "${GREEN}=========================================="
echo "VPS Setup Complete!"
echo "==========================================${NC}"
echo ""
echo "Next steps:"
echo ""
echo "1. Copy your prerender server.js to:"
echo "   $PRERENDER_DIR/server.js"
echo ""
echo "2. Edit server.js and set your SPA_URL:"
echo "   SPA_URL: https://$DOMAIN"
echo ""
echo "3. Build and upload your React app:"
echo "   npm run build"
echo "   rsync -avz dist/* $USER@$(hostname):$SPA_DIR/"
echo ""
echo "4. Start the prerender service:"
echo "   cd $PRERENDER_DIR && pm2 start server.js --name prerender"
echo "   pm2 save"
echo ""
echo "5. Get SSL certificate:"
echo "   sudo certbot --nginx -d $DOMAIN -d www.$DOMAIN"
echo ""
echo "6. Reload Nginx:"
echo "   sudo systemctl reload nginx"
echo ""
echo "7. Test prerendering:"
echo "   curl -A 'Googlebot' https://$DOMAIN/"
echo ""
